version: '3.8'

services:
#  wishlist-service:
#    build: .
#    ports:
#      - "8080:8080"
#    depends_on:
#      - mongodb
#    environment:
#      - SPRING_DATA_MONGODB_URI=mongodb://mongodb:27017/wishlist

  mongodb:
    image: mongo:4.4
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    environment:
      - SPRING_DATA_MONGODB_URI=mongodb://mongodb:27017/wishlist

volumes:
  mongo-data:
